services:
  servidor-web:
    build:
      context: .
    container_name: contratos-nginx-https
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    volumes:
      - ./certs:/etc/nginx/ssl:ro
    restart: unless-stopped
